### ISSUE TITLE
malformed URL error for git+ssh://user@host:/path/foo.git

### ISSUE THREAD

**Issue by yaccz** [neithernut/git-dit#186] opened 2019-06-04 01:30 UTC
```
yac@remy % git init foo
Initialized empty Git repository in /home/yac/foo/.git/
yac@remy % cd foo
yac@remy % git remote add origin git+ssh://user@host:/path/foo.git
yac@remy % git dit fetch origin
malformed URL 'git+ssh://user@host:/path/foo.git'; class=Net (12); code=InvalidSpec (-12)
```

**Comment by neithernut** [comment] 2019-06-04 07:43
Thanks for the report! Will investigate as soon as I'm back from work.

In the meantime you can add the following refspec line to the `[remote "origin"]` section of your local repos `.git/config`:

    fetch = +refs/dit/*:refs/remotes/origin/dit/*

It will cause git to fetch the "dit" refs we use on a regular fetch.

----

Sidenote: we planned to add a "subscription" feature which adds that refspec to the config in a more user-friendly way.

**Comment by yaccz** [comment] 2019-06-04 14:49
This looks like a workaround. Is this a workaround or something to help you debug?
I am in the evaluation phase right now so I don't mind waiting a bit for fix.
fyi I encountered this issue when trying a push. I used fetch in the example since it exhibits the same issue and is simpler to set up.

**Comment by neithernut** [comment] 2019-06-04 16:12
> This looks like a workaround. Is this a workaround or something to help you debug?

It's a workaround. Kinda. Actually, that's how I set up remotes for git-dit for myself. I think I never really used `git dit push` and `git dit fetch`, apart from testing its functionality.

**Comment by neithernut** [comment] 2019-06-04 17:47
I can reproduce. The error apparently also occurs with other schemas (including `ssh://`). URLs like `user@host:/path/foo.git` appear to work fine, at least for ssh. I suspect this _will_ take some time.

The error likely originates from [libgit2](https://github.com/libgit2/libgit2). So far I've found three possible origins: in the [ssh](https://github.com/libgit2/libgit2/blob/bc5b19e60406b2b0b7173d866a808313fca2b4ce/src/transports/ssh.c#L282), [git](https://github.com/libgit2/libgit2/blob/6853a250071dbacd54e08235c1e12da622e6ca8d/src/transports/git.c#L50) transports and in [netopts.c](https://github.com/libgit2/libgit2/blob/635693d3bc55770ec7a6640ba3f2f0ee434a6042/src/netops.c#L238). Interestingly, the only one setting the `InvalidSpec` error code appears to be the last one, but it could as well be set further up the stack.

**Comment by neithernut** [comment] 2019-06-08 08:56
I just started investigating the issue some more. The error _is_ emitted in [netopts.c](https://github.com/libgit2/libgit2/blob/b3e1a56ebb2b9291e82dc027ba9cbcfc3ead54d3/src/netops.c#L237). Apparently [http_parser_parse_url](https://github.com/libgit2/libgit2/blob/b3e1a56ebb2b9291e82dc027ba9cbcfc3ead54d3/deps/http-parser/http_parser.c#L2062) fails to parse the host ([here](https://github.com/libgit2/libgit2/blob/b3e1a56ebb2b9291e82dc027ba9cbcfc3ead54d3/deps/http-parser/http_parser.c#L2135)) using [http_parse_host](https://github.com/libgit2/libgit2/blob/b3e1a56ebb2b9291e82dc027ba9cbcfc3ead54d3/deps/http-parser/http_parser.c#L1989). In there, everything works fine until we reach some [sanity check](https://github.com/libgit2/libgit2/blob/b3e1a56ebb2b9291e82dc027ba9cbcfc3ead54d3/deps/http-parser/http_parser.c#L2046). As we end up at the beginning of the "port" field, the check fails.

I'll report this upstream, but it will take a while until we benefit from a fix, since we have to wait for a [git2-rs](https://github.com/rust-lang/git2-rs) to pick up the fix/the next release. I'll leave this issue open until the changes have reached us.

A workaround is to use the schema-less form for ssh origins (e.g. `user@host:/path/foo.git`) or without the (empty) port (e,g, `ssh://user@host/path/foo.git`). Also note that using the `ssh+git` schema is generally discouraged.

**Comment by neithernut** [comment] 2019-06-08 09:28
I just reported the issue upstream: libgit2/libgit2#5100

**Comment by neithernut** [comment] 2019-08-21 19:50
The underlying issue was fixed in https://github.com/libgit2/libgit2, a fixed version was picked up by https://github.com/rust-lang/git2-rs (0.9.2 or later). A `cargo update` and rebuild should resolve the issue.

I can't test it right now due to other issues. However, I'll close this issue regardless. Please reopen if the issue persists.

**Closed by neithernut** 2019-08-21 19:50 UTC
